from __future__ import annotations

_CLOCK_AND_DATE_MARKERS = (
    "what day is it",
    "what day is today",
    "what is the day today",
    "today's date",
    "date today",
    "what time is it",
    "what's the time",
    "time now",
)

_WEATHER_MARKERS = (
    " weather ",
    " weather?",
    "weather ",
    " forecast",
    " temperature",
    " rain ",
    " rain?",
    " raining",
    " rainy",
    " snow ",
    " snow?",
    " snowing",
    " snowy",
    " wind ",
    " windy",
    " humidity",
    " humid ",
    " sunrise",
    " sunset",
    " wheather",
    " wheater",
    " whether today",
    " whether now",
    " whether in ",
)

_NEWS_MARKERS = (
    "latest news",
    "breaking news",
    "headlines",
    "headline",
    "news on",
    "news about",
    "what happened today",
    "what's the latest on",
    "what is the latest on",
    "whats the latest on",
    "latest on ",
    "latest about ",
)

_LIVE_LOOKUP_HINT_MARKERS = (
    "look up",
    "check online",
    "search online",
    "browse",
)

_FRESH_LOOKUP_MARKERS = (
    "release notes",
    "changelog",
    "latest update",
    "latest updates",
    "current version",
    "latest version",
    "status page",
    "current price",
    "price now",
    "price today",
    "price right now",
    "exchange rate",
    "how much is",
    "how much does",
    "worth right now",
    "worth today",
    "worth now",
    "market price",
    "stock price",
    "oil price",
    "gold price",
    "bitcoin price",
    "btc price",
    "eth price",
    "crypto price",
)

_LATEST_DOMAIN_MARKERS = (
    "api",
    "sdk",
    "library",
    "package",
    "release",
    "version",
    "bot",
    "telegram",
    "discord",
    "model",
    "framework",
    "price",
    "stock",
)
